parameters:
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $routing: !tagged_iterator { tag: app.routing, default_priority_method: getPriority }
            $workerPath: '%kernel.project_dir%/bin/worker.php'
            $tmpPath:  '%kernel.project_dir%/var/tmp'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Server'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Action/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Routing\Specs\RoutingInterface:
            tags: ['app.routing']

    App\Server\ServerStartCommand: ~
    App\Server\RequestHandler: ~
